### ISSUE TITLE
Error in log: sun2: Error on device update!

### ISSUE THREAD

**Issue by gerritjonker** [pnbruckner/ha-sun2#42]
HA version: core-2021.5.4. Sun2 2.0.0.0.
The message appears only after HA restart and is logged twice at exactly the same time.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/astral/sun.py", line 862, in dusk
    return time_of_transit(
  File "/usr/local/lib/python3.8/site-packages/astral/sun.py", line 343, in time_of_transit
    hourangle = hour_angle(
  File "/usr/local/lib/python3.8/site-packages/astral/sun.py", line 243, in hour_angle
    HA = acos(h)
ValueError: math domain error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 407, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 516, in async_device_update
    await task
  File "/config/custom_components/sun2/sensor.py", line 182, in async_update
    self._update()
  File "/config/custom_components/sun2/sensor.py", line 198, in _update
    super()._update()
  File "/config/custom_components/sun2/sensor.py", line 176, in _update
    self._yesterday = self._get_data(today - _ONE_DAY)
  File "/config/custom_components/sun2/sensor.py", line 172, in _get_data
    return self._get_astral_event(self._event, date_or_dt)
  File "/config/custom_components/sun2/sensor.py", line 169, in _get_astral_event
    return astral_event(self._info, event, date_or_dt, self._solar_depression)
  File "/config/custom_components/sun2/helpers.py", line 69, in astral_event
    return getattr(loc, event)(date_or_dt, observer_elevation=elev)
  File "/usr/local/lib/python3.8/site-packages/astral/location.py", line 416, in dusk
    return astral.sun.dusk(observer, date, self.solar_depression, self.tzinfo)
  File "/usr/local/lib/python3.8/site-packages/astral/sun.py", line 867, in dusk
    raise ValueError(
ValueError: Sun never reaches 18.0 degrees below the horizon, at this location.

**Comment by pnbruckner** [comment]
Fixed in [2.0.1](https://github.com/pnbruckner/ha-sun2/releases/tag/2.0.1)
